name: Update Fuchs2 Calendar

on:
  schedule:
    # Triggers automatically every day at 4:30 AM UTC (30 min after Bike Jesus)
    - cron: '30 4 * * *'
  workflow_dispatch: # Enables manual trigger button inside the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository source code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install required dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests ics

    - name: Execute Fuchs2 Parser script
      # Change directory to fuchs2 and run the script
      run: |
        cd scripts
        python fuchs2.py

    - name: Commit and push updated files (Calendar + Archive)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        git fetch origin
        git checkout data || git checkout -b data origin/data || git checkout -b data
        git add fuchs2-calendar.ics fuchs2-archive.json
        git commit -m "Automated Fuchs2 database & calendar update [skip ci]" || exit 0
        git push